sudo: false
language: elixir
elixir:
  - 1.7.3
  - 1.7
otp_release:
  - 20.3
  - 21.1
script:
  - mix deps.compile
  - mix compile
  - MIX_ENV=test mix compile
  - mix format --check-formatted
  - mix credo
  - mix test
